import 'dart:convert';
import 'dart:io';

/// Post-processes the validated sing-box JSON config generated by hiddify-core:
/// 1. TUIC: hiddify-core v4.1.0 converts tls.alpn array → string; fix back to array.
/// 2. XHTTP: sing-box 1.13.x doesn't support xhttp transport; remove those outbounds
///    and their tags from all selector/urltest groups so they don't show red stars.
class LimmConfigPatcher {
  LimmConfigPatcher._();

  static Future<void> patchFile(String path) async {
    final file = File(path);
    if (!await file.exists()) return;
    try {
      final raw = await file.readAsString();
      final config = jsonDecode(raw) as Map<String, dynamic>;
      if (_patch(config)) {
        await file.writeAsString(jsonEncode(config));
      }
    } catch (_) {}
  }

  static bool _patch(Map<String, dynamic> config) {
    final outbounds = config['outbounds'];
    if (outbounds is! List) return false;
    bool changed = false;
    final xhttpTags = <String>{};

    for (final ob in outbounds.cast<Map<String, dynamic>>()) {
      if (ob['type'] == 'tuic') {
        if (_fixTuicAlpn(ob)) changed = true;
      } else if (ob['type'] == 'vless' &&
          (ob['transport'] as Map?)?['type'] == 'xhttp') {
        final tag = ob['tag'] as String?;
        if (tag != null && tag.isNotEmpty) xhttpTags.add(tag);
      }
    }

    if (xhttpTags.isNotEmpty) {
      final before = outbounds.length;
      outbounds.removeWhere((ob) => xhttpTags.contains((ob as Map)['tag']));
      if (outbounds.length != before) changed = true;
      for (final ob in outbounds.cast<Map<String, dynamic>>()) {
        final t = ob['type'] as String?;
        if (t == 'selector' || t == 'urltest') {
          final items = ob['outbounds'] as List?;
          if (items != null) {
            final b2 = items.length;
            items.removeWhere((tag) => xhttpTags.contains(tag));
            if (items.length != b2) changed = true;
          }
        }
      }
    }

    return changed;
  }

  static bool _fixTuicAlpn(Map<String, dynamic> ob) {
    final tls = ob['tls'] as Map<String, dynamic>?;
    if (tls == null) return false;
    final alpn = tls['alpn'];
    if (alpn is String) {
      tls['alpn'] = [alpn];
      return true;
    }
    return false;
  }
}
