import 'dart:convert';
import 'dart:io';

/// Post-processes the validated sing-box JSON config generated by hiddify-core:
/// 1. TUIC: ensure tls.alpn = ["h3"]. hiddify-core emits TUIC outbounds WITHOUT alpn
///    (or as a bare string); sing-box then negotiates the wrong/empty QUIC ALPN and the
///    tuic-server replies APPLICATION_ERROR. Force the array ["h3"].
/// 2. XHTTP: the server side is xray-native xhttp, but hiddify-core maps the xhttp URI to a
///    sing-box `transport.type == "http"` (HTTP/2) outbound — incompatible with xray xhttp,
///    so those profiles always fail (red star). Remove them and their tags from
///    selector/urltest groups so they're hidden instead of shown broken. Detected by the
///    `-xhttp` tag (the sing-box transport type is "http", NOT "xhttp").
class LimmConfigPatcher {
  LimmConfigPatcher._();

  static Future<void> patchFile(String path) async {
    final file = File(path);
    if (!await file.exists()) return;
    try {
      final raw = await file.readAsString();
      final config = jsonDecode(raw) as Map<String, dynamic>;
      if (_patch(config)) {
        await file.writeAsString(jsonEncode(config));
      }
    } catch (_) {}
  }

  static bool _patch(Map<String, dynamic> config) {
    final outbounds = config['outbounds'];
    if (outbounds is! List) return false;
    bool changed = false;
    final xhttpTags = <String>{};

    for (final ob in outbounds.cast<Map<String, dynamic>>()) {
      if (ob['type'] == 'tuic') {
        if (_fixTuicAlpn(ob)) changed = true;
      } else if (_isXhttp(ob)) {
        final tag = ob['tag'] as String?;
        if (tag != null && tag.isNotEmpty) xhttpTags.add(tag);
      }
    }

    if (xhttpTags.isNotEmpty) {
      final before = outbounds.length;
      outbounds.removeWhere((ob) => xhttpTags.contains((ob as Map)['tag']));
      if (outbounds.length != before) changed = true;
      for (final ob in outbounds.cast<Map<String, dynamic>>()) {
        final t = ob['type'] as String?;
        if (t == 'selector' || t == 'urltest') {
          final items = ob['outbounds'] as List?;
          if (items != null) {
            final b2 = items.length;
            items.removeWhere((tag) => xhttpTags.contains(tag));
            if (items.length != b2) changed = true;
          }
        }
      }
    }

    return changed;
  }

  /// xhttp profiles: tag carries `-xhttp` but hiddify-core emits transport.type "http"
  /// (HTTP/2), not "xhttp" — so match on the tag (with the transport check as a backup).
  static bool _isXhttp(Map<String, dynamic> ob) {
    final tag = (ob['tag'] as String? ?? '').toLowerCase();
    if (tag.contains('xhttp')) return true;
    final tr = ob['transport'] as Map?;
    return ob['type'] == 'vless' && (tr?['type'] == 'xhttp');
  }

  /// TUIC needs QUIC ALPN "h3" as an array. Add it when missing or wrap a bare string.
  static bool _fixTuicAlpn(Map<String, dynamic> ob) {
    final tls = ob['tls'] as Map<String, dynamic>?;
    if (tls == null) return false;
    final alpn = tls['alpn'];
    if (alpn is List) {
      if (alpn.isNotEmpty) return false; // already a proper array
      tls['alpn'] = ['h3'];
      return true;
    }
    if (alpn is String) {
      tls['alpn'] = [alpn];
      return true;
    }
    // missing entirely
    tls['alpn'] = ['h3'];
    return true;
  }
}
